# Generated by Django 4.2.6 on 2023-11-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="additional_text",
            field=models.TextField(
                default="MISSING", verbose_name="Add Additional Information"
            ),
        ),
    ]
