# Generated by Django 4.2.6 on 2023-11-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_choice_additional_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="additional_text",
            field=models.TextField(
                default="no comments", verbose_name="Add Additional Information"
            ),
        ),
    ]
