# Generated by Django 4.2.6 on 2023-11-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_alter_choice_additional_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=100)),
                (
                    "Description",
                    models.TextField(
                        default=" ", verbose_name="A detailed description of the task."
                    ),
                ),
                ("DueDate", models.DateTimeField(verbose_name="Due Date")),
            ],
        ),
    ]
