# Generated by Django 4.2.6 on 2023-11-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_name", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=200)),
                ("completed", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(name="TodoItem",),
    ]
