# Generated by Django 4.2.6 on 2023-11-07 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_name", "0002_task_delete_todoitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task", old_name="content", new_name="title",
        ),
    ]
