# Generated by Django 4.2.6 on 2023-11-08 22:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("social", "0002_post_likes_alter_like_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                default=5, related_name="liked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
