# Generated by Django 4.2.6 on 2023-11-08 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0004_alter_post_likes"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="likes",),
    ]
