# Generated by Django 4.2.6 on 2023-11-10 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0005_remove_post_likes"),
    ]

    operations = [
        migrations.DeleteModel(name="Like",),
    ]
