# Generated by Django 4.2.6 on 2023-11-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0016_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
