# Generated by Django 4.2.6 on 2023-11-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0017_alter_userprofile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="images/profile_pictures/default.png",
                null=True,
                upload_to="images/profile_pictures/",
            ),
        ),
    ]
