# Generated by Django 4.2.6 on 2023-11-10 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_alter_image_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="date_posted",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
